FROM perl:5.36

RUN cpanm Dist::Zilla
RUN cpanm Dist::Zilla::Plugin::Config::Git
RUN cpanm Dist::Zilla::Plugin::ConfirmRelease
RUN cpanm Dist::Zilla::Plugin::CPANFile
RUN cpanm Dist::Zilla::Plugin::ExtraTests
RUN cpanm Dist::Zilla::Plugin::GatherDir
RUN cpanm Dist::Zilla::Plugin::GitHub::Meta
RUN cpanm Dist::Zilla::Plugin::Git::Tag
RUN cpanm Dist::Zilla::Plugin::License
RUN cpanm Dist::Zilla::Plugin::MakeMaker
RUN cpanm Dist::Zilla::Plugin::Manifest
RUN cpanm Dist::Zilla::Plugin::MetaJSON
RUN cpanm Dist::Zilla::Plugin::MetaProvides::Package
RUN cpanm Dist::Zilla::Plugin::MetaYAML
RUN cpanm Dist::Zilla::Plugin::PkgVersion
RUN cpanm Dist::Zilla::Plugin::Pod2Readme
RUN cpanm Dist::Zilla::Plugin::PodSyntaxTests
RUN cpanm Dist::Zilla::Plugin::Prereqs
RUN cpanm Dist::Zilla::Plugin::PruneCruft
RUN cpanm Dist::Zilla::Plugin::TestRelease
RUN cpanm Dist::Zilla::Plugin::UploadToCPAN
